name: My first workflow
on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              uses: echo "My first GitHub Action workflow!"

            - name: list files
              run: ls 
              
            - name: read file
              run: cat README.md