name: My first workflow
on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              
            - name: List and Read Files
              run: |
                echo "Listing files in the repository:"
                ls-Itra
                cat README.md

            - name: Generate ASCII Artwork
              run: cowsay -f dragon"Hello World">>dragon.txt
            #- name: list files
             # run: ls 
              
            #- name: read file
             # run: cat README.md